### PR TITLE
🍱 Add 5 new gitmojis

### PR DESCRIPTION
**Pull request by indifferentalex**
🌱🚩🥅💫🗑

### CODE REVIEW

**Comment by indifferentalex** [comment]
CC: @peterfication @tomhoule @fnune

**Review by fnune — APPROVED** [review]

**Review by peterfication — APPROVED** [review]
💯

**Comment by indifferentalex** [comment]
@fnune @peterfication I can't seem to merge, could you do it?

**Comment by fnune** [comment]
> @fnune @peterfication I can't seem to merge, could you do it?

Done!

**Pull request merged**
